// Code generated by goctl. DO NOT EDIT.
package types

type GetAllUserRequest struct {
}

type GetAllUsersResponse struct {
	Users []User `json:"users"`
}

type GetUserByIdRequest struct {
	ID string `json:"id",optional`
}

type GetUserByIdResponse struct {
	ID       string `json:"id"`
	FNAME    string `json:"fname"`
	LNAME    string `json:"lname"`
	AGE      int32  `json:"age"`
	BDATE    string `json:"bdate"`
	UpdateAt string `json:"updateAt"`
	CreateAt string `json:"createAt"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type User struct {
	ID       string `json:"id"`
	FNAME    string `json:"fname"`
	LNAME    string `json:"lname"`
	AGE      int32  `json:"age"`
	BDATE    string `json:"bdate"`
	UpdateAt string `json:"updateAt"`
	CreateAt string `json:"createAt"`
}
