// Code generated by goctl. DO NOT EDIT.
package types

type DeleteUserByIdRequest struct {
	ID string `path:"id"`
}

type DeleteUserByIdResponse struct {
	Message string `json:"message"`
}

type GetAllUserRequest struct {
}

type GetAllUsersResponse struct {
	Users []User `json:"users"`
}

type GetUserByIdRequest struct {
	ID string `json:"id"`
}

type GetUserByIdResponse struct {
	User
}

type NewUserRequest struct {
	User
}

type NewUserResponse struct {
	Message string `json:"message"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type User struct {
	ID       string `json:"id,omitempty"`
	FNAME    string `json:"fname"`
	LNAME    string `json:"lname"`
	AGE      int32  `json:"age"`
	BDATE    string `json:"bdate"`
	UpdateAt string `json:"updateAt,omitempty"`
	CreateAt string `json:"createAt,omitempty"`
}
