// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"test.com/rpc/internal/logic"
	"test.com/rpc/internal/svc"
	"test.com/rpc/pb/user"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) Ping(ctx context.Context, in *user.Request) (*user.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *UserServiceServer) GetUserById(ctx context.Context, in *user.GetUserByIdRequest) (*user.GetUserByIdResponse, error) {
	l := logic.NewGetUserByIdLogic(ctx, s.svcCtx)
	return l.GetUserById(in)
}

func (s *UserServiceServer) GetAllUsers(ctx context.Context, in *user.GetAllUserRequest) (*user.GetAllUsersResponse, error) {
	l := logic.NewGetAllUsersLogic(ctx, s.svcCtx)
	return l.GetAllUsers(in)
}
